### ISSUE TITLE
What algorithm is CelebA-HQ256_DFE generated by?

### ISSUE THREAD

**Issue by aidreamwin** [tenten0727/Sketch-to-diverse-image#1]
Thank you so much for open-sourcing such an excellent project. When I study this project, I need to use my own dataset. I want to know what algorithm is used to generate a dataset similar to CelebA-HQ256_DFE. It would be better if there is a demo or code. Ths...

**Comment by tenten0727** [comment]
Thank you for your interest in our research. We also apologize for the delay in responding to you.

CelebA-HQ256_DFE was extracted using the code in Deep Face Editing implementation.
https://github.com/IGLICT/DeepFaceEditing-Jittor#extract-sketches-from-real-images

**Comment by aidreamwin** [comment]
> Thank you for your interest in our research. We also apologize for the delay in responding to you.
> 
> CelebA-HQ256_DFE was extracted using the code in Deep Face Editing implementation. https://github.com/IGLICT/DeepFaceEditing-Jittor#extract-sketches-from-real-images

Thanks for your help.
